<script lang="ts">
  import { onMount } from 'svelte';
  import { gameStore } from '$lib/stores/gameStore';
  import type { ID, StatType, GameData, Player } from '$lib/types';
  import type { PageData } from './$types'; // generated by SvelteKit

  /* props from +page.ts load */
  let { data }: { data: PageData } = $props();
  const gameId: ID = data.id as ID;

  /* local reactive state */
  let period = $state(1);
  let game: GameData | null = $state(null);

  /* subscribe to the actual Svelte store */
  const currentGameStore = gameStore.currentGame;
  $effect(() => {
    const unsub = currentGameStore.subscribe((v) => (game = v));
    return unsub;
  });

  /* load game once mounted in the browser (reads local storage) */
  onMount(() => {
    if (gameId) gameStore.loadGame(gameId);
  });

  /* derived values recompute when `game` changes */
  type Totals = {
    goals: number;
    shots: number;
    assists: number;
    blocks: number;
    steals: number;
    turnovers: number;
    exclusions: number;
    drawnExclusions: number;
  };
  type PlayerTotalsMap = Record<ID, Totals>;
  type Score = { home: number; opponent: number };

  const playerTotals: PlayerTotalsMap = $derived(
    game ? computePlayerTotals(game) : ({} as PlayerTotalsMap)
  );

  const teamScore: Score = $derived(
    game ? computeTeamScore(game) : { home: 0, opponent: 0 }
  );

  /* Active vs Bench derived lists (undefined => active by default) */
  const activePlayers = $derived<Player[]>(() =>
    game
      ? game.home.players.filter((p) => p.active !== false) // true or undefined -> active
      : []
  );
  const benchPlayers = $derived<Player[]>(() =>
    game
      ? game.home.players.filter((p) => p.active === false)
      : []
  );

  function logStat(playerId: ID | undefined, type: StatType) {
    if (!game) return;
    const teamId = playerId ? game.home.id : game.opponent.id;
    gameStore.addEvent({
      gameId: game.meta.id,
      teamId,
      playerId,
      type,
      period
    });
  }

  function nextPeriod() {
    if (!game) return;
    if (period < game.meta.periods) period += 1;
  }
  function prevPeriod() {
    if (period > 1) period -= 1;
  }
  function undo() {
    gameStore.undoLast();
  }

  /** Toggle player.active and persist game. */
  function setPlayerActive(id: ID, isActive: boolean) {
    if (!game) return;
    const g = structuredClone(game) as GameData;
    const player = g.home.players.find((p) => p.id === id);
    if (!player) return;
    player.active = isActive;
    gameStore.saveGame(g); // triggers store update
  }

  // --- helpers ---
  function emptyTotals(): Totals {
    return {
      goals: 0,
      shots: 0,
      assists: 0,
      blocks: 0,
      steals: 0,
      turnovers: 0,
      exclusions: 0,
      drawnExclusions: 0
    };
  }

  function computePlayerTotals(g: GameData): PlayerTotalsMap {
    const totals: PlayerTotalsMap = {} as PlayerTotalsMap;
    for (const p of g.home.players) {
      totals[p.id] = emptyTotals();
    }
    for (const e of g.events) {
      if (!e.playerId) continue;
      const t = totals[e.playerId];
      if (!t) continue;
      switch (e.type) {
        case 'GOAL': t.goals++; break;
        case 'SHOT': t.shots++; break;
        case 'ASSIST': t.assists++; break;
        case 'BLOCK': t.blocks++; break;
        case 'STEAL': t.steals++; break;
        case 'TURNOVER': t.turnovers++; break;
        case 'EXCLUSION': t.exclusions++; break;
        case 'DRAWN_EXCLUSION': t.drawnExclusions++; break;
      }
    }
    return totals;
  }

  function computeTeamScore(g: GameData): Score {
    let home = 0;
    let opponent = 0;
    for (const e of g.events) {
      if (e.type !== 'GOAL') continue;
      if (e.teamId === g.home.id) home++; else opponent++;
    }
    return { home, opponent };
  }

  /* stop bubbling from mini-buttons so tile click doesn't also log a Goal */
  function stop<E extends Event>(e: E) {
    e.stopPropagation();
  }

  /** If player is bench, clicking tile activates them; otherwise logs GOAL. */
  function tileClick(p: Player) {
    if (p.active === false) {
      setPlayerActive(p.id, true);
    } else {
      logStat(p.id, 'GOAL');
    }
  }
</script>

{#if !game}
  <p class="p-4 text-center text-lg text-slate-500">Loading...</p>
{:else}
  <div class="space-y-6 max-w-5xl mx-auto">
    <!-- Scoreboard -->
    <div class="grid grid-cols-3 items-center gap-2 text-center">
      <div class="truncate text-xl font-semibold">{game.home.name}</div>
      <div class="text-3xl font-bold">{teamScore.home} : {teamScore.opponent}</div>
      <div class="truncate text-xl font-semibold">{game.opponent.name}</div>
    </div>

    <!-- Period Controls -->
    <div class="flex items-center justify-center gap-4">
      <button
        type="button"
        onclick={prevPeriod}
        class="px-3 py-1 rounded bg-slate-300 text-slate-800 disabled:opacity-40"
        disabled={period === 1}
      >-</button>
      <div class="text-lg font-medium">Period {period} / {game.meta.periods}</div>
      <button
        type="button"
        onclick={nextPeriod}
        class="px-3 py-1 rounded bg-slate-300 text-slate-800 disabled:opacity-40"
        disabled={period >= game.meta.periods}
      >+</button>
    </div>

    <!-- ACTIVE PLAYERS + OPPONENT COLUMN -->
    <div class="grid grid-cols-1 md:grid-cols-[1fr_auto] gap-4 items-start">
      <!-- Active Players -->
      <div class="space-y-2">
        <h2 class="text-lg font-semibold px-1">Active ({activePlayers.length})</h2>
        <div class="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3">
          {#each activePlayers as p}
            <PlayerTile {p} isActive={true} />
          {/each}
        </div>
      </div>

      <!-- Opponent Column (desktop / tablet landscape) -->
      <div class="hidden md:flex md:self-start flex-col items-center gap-2 w-36 text-center">
        <h3 class="text-sm font-semibold truncate max-w-full">{game.opponent.name}</h3>

        <!-- row 1 -->
        <div class="grid grid-cols-1 gap-2 w-full">
          <button
            type="button"
            class="w-full py-2 rounded bg-slate-800 text-white font-bold"
            onclick={() => logStat(undefined,'GOAL')}
          >Opp Goal</button>
          <button
            type="button"
            class="w-full py-2 rounded bg-slate-800 text-white font-bold"
            onclick={() => logStat(undefined,'SHOT')}
          >Opp Shot</button>
          <button
            type="button"
            class="w-full py-2 rounded bg-slate-800 text-white font-bold"
            onclick={() => logStat(undefined,'ASSIST')}
          >Opp Ast</button>
        </div>

        <!-- row 2 -->
        <div class="grid grid-cols-1 gap-2 w-full mt-2">
          <button
            type="button"
            class="w-full py-2 rounded bg-slate-800 text-white font-bold"
            onclick={() => logStat(undefined,'BLOCK')}
          >Opp Blk</button>
          <button
            type="button"
            class="w-full py-2 rounded bg-slate-800 text-white font-bold"
            onclick={() => logStat(undefined,'STEAL')}
          >Opp Stl</button>
          <button
            type="button"
            class="w-full py-2 rounded bg-slate-800 text-white font-bold"
            onclick={() => logStat(undefined,'DRAWN_EXCLUSION')}
          >Opp DEx</button>
        </div>

        <!-- divider -->
        <div class="w-full h-px bg-slate-300 my-1"></div>

        <!-- row 3 (negative) -->
        <div class="grid grid-cols-1 gap-2 w-full">
          <button
            type="button"
            class="w-full py-2 rounded bg-red-600 text-white font-bold"
            onclick={() => logStat(undefined,'TURNOVER')}
          >Opp TO</button>
          <button
            type="button"
            class="w-full py-2 rounded bg-red-700 text-white font-bold"
            onclick={() => logStat(undefined,'EXCLUSION')}
          >Opp Ex</button>
        </div>
      </div>
    </div>

    <!-- BENCH PLAYERS -->
    <div class="space-y-2">
      <h2 class="text-lg font-semibold px-1">Bench ({benchPlayers.length})</h2>
      {#if benchPlayers.length === 0}
        <p class="text-sm text-slate-500 px-1">No bench players.</p>
      {:else}
        <div class="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3">
          {#each benchPlayers as p}
            <PlayerTile {p} isActive={false} />
          {/each}
        </div>
      {/if}
    </div>

    <!-- Opponent Rows (mobile fallback) -->
    <div class="md:hidden space-y-2 mt-4">
      <!-- row 1 -->
      <div class="grid grid-cols-3 gap-2">
        <button type="button" class="py-3 rounded bg-slate-800 text-white font-bold" onclick={() => logStat(undefined,'GOAL')}>G</button>
        <button type="button" class="py-3 rounded bg-slate-800 text-white font-bold" onclick={() => logStat(undefined,'SHOT')}>S</button>
        <button type="button" class="py-3 rounded bg-slate-800 text-white font-bold" onclick={() => logStat(undefined,'ASSIST')}>A</button>
      </div>
      <!-- row 2 -->
      <div class="grid grid-cols-3 gap-2">
        <button type="button" class="py-3 rounded bg-slate-800 text-white font-bold" onclick={() => logStat(undefined,'BLOCK')}>B</button>
        <button type="button" class="py-3 rounded bg-slate-800 text-white font-bold" onclick={() => logStat(undefined,'STEAL')}>St</button>
        <button type="button" class="py-3 rounded bg-slate-800 text-white font-bold" onclick={() => logStat(undefined,'DRAWN_EXCLUSION')}>DEx</button>
      </div>
      <!-- row 3 negative -->
      <div class="grid grid-cols-2 gap-2">
        <button type="button" class="py-3 rounded bg-red-600 text-white font-bold" onclick={() => logStat(undefined,'TURNOVER')}>TO</button>
        <button type="button" class="py-3 rounded bg-red-700 text-white font-bold" onclick={() => logStat(undefined,'EXCLUSION')}>Ex</button>
      </div>
    </div>

    <!-- Controls -->
    <div class="flex gap-4 justify-center pt-4">
      <button type="button" class="px-4 py-2 rounded bg-amber-500 text-white font-semibold" onclick={undo}>Undo</button>
      <a href="/export/{game.meta.id}" class="px-4 py-2 rounded bg-blue-600 text-white font-semibold text-center">Export</a>
    </div>
  </div>
{/if}

<!-- Player Tile Inline Component -->
<script module lang="ts">
  import type { Player } from '$lib/types';

  export let p: Player;
  export let isActive: boolean;

  /* these outer-scope funcs/vars are hoisted from the main script */
  // logStat, stop, playerTotals, setPlayerActive, tileClick come from outer script
</script>

<!--
  NOTE: Because Svelte single-file components don't have a dedicated child component
  block (without creating a separate file), we emulate a "componentlet" using
  {@html} would lose reactivity. Instead, we inline the markup in the #each loops above.
  The <script module> block above is inert; kept only if you decide to factor out.

  => The actual PlayerTile DOM is rendered inline in the #each loops; see markup there.
-->
