<script lang="ts">
  import { onMount } from 'svelte';
  import { gameStore } from '$lib/stores/gameStore';
  import type { ID, StatType, GameData } from '$lib/types';
  import type { PageData } from './$types'; // generated by SvelteKit

  /* props from +page.ts load */
  let { data }: { data: PageData } = $props();
  const gameId: ID = data.id as ID;

  /* local reactive state */
  let period = $state(1);
  let game: GameData | null = $state(null);

  /* subscribe to the actual Svelte store */
  const currentGameStore = gameStore.currentGame;
  $effect(() => {
    const unsub = currentGameStore.subscribe((v) => (game = v));
    return unsub;
  });

  /* load game once mounted in the browser (reads local storage) */
  onMount(() => {
    if (gameId) gameStore.loadGame(gameId);
  });

  /* derived values recompute when `game` changes */
  type Totals = { goals: number; shots: number; assists: number; blocks: number };
  type PlayerTotalsMap = Record<ID, Totals>;
  type Score = { home: number; opponent: number };

  const playerTotals: PlayerTotalsMap = $derived(
    game ? computePlayerTotals(game) : ({} as PlayerTotalsMap)
  );

  const teamScore: Score = $derived(
    game ? computeTeamScore(game) : { home: 0, opponent: 0 }
  );

  function logStat(playerId: ID | undefined, type: StatType) {
    if (!game) return;
    const teamId = playerId ? game.home.id : game.opponent.id;
    gameStore.addEvent({
      gameId: game.meta.id,
      teamId,
      playerId,
      type,
      period
    });
  }

  function nextPeriod() {
    if (!game) return;
    if (period < game.meta.periods) period += 1;
  }
  function prevPeriod() {
    if (period > 1) period -= 1;
  }
  function undo() {
    gameStore.undoLast();
  }

  // --- helpers ---
  function computePlayerTotals(g: GameData): PlayerTotalsMap {
    const totals: PlayerTotalsMap = {} as PlayerTotalsMap;
    for (const p of g.home.players) {
      totals[p.id] = { goals: 0, shots: 0, assists: 0, blocks: 0 };
    }
    for (const e of g.events) {
      if (!e.playerId) continue;
      const t = totals[e.playerId];
      if (!t) continue;
      switch (e.type) {
        case 'GOAL': t.goals++; break;
        case 'SHOT': t.shots++; break;
        case 'ASSIST': t.assists++; break;
        case 'BLOCK': t.blocks++; break;
      }
    }
    return totals;
  }

  function computeTeamScore(g: GameData): Score {
    let home = 0;
    let opponent = 0;
    for (const e of g.events) {
      if (e.type !== 'GOAL') continue;
      if (e.teamId === g.home.id) home++; else opponent++;
    }
    return { home, opponent };
  }
</script>

{#if !game}
  <p class="p-4 text-center text-lg text-slate-500">Loading...</p>
{:else}
  <div class="space-y-6 max-w-4xl mx-auto">
    <!-- Scoreboard -->
    <div class="grid grid-cols-3 items-center gap-2 text-center">
      <div class="truncate text-2xl text-green-700 font-semibold">{game.home.name}</div>
      <div class="text-3xl font-bold">{teamScore.home} : {teamScore.opponent}</div>
      <div class="truncate text-2xl text-blue-800 font-semibold">{game.opponent.name}</div>
    </div>

    <!-- Period Controls -->
    <div class="flex items-center justify-center gap-4">
      <button
        type="button"
        onclick={prevPeriod}
        class="px-3 py-1 rounded bg-slate-300 text-slate-800 disabled:opacity-40"
        disabled={period === 1}
      >-</button>
      <div class="text-lg font-medium">Period {period} / {game.meta.periods}</div>
      <button
        type="button"
        onclick={nextPeriod}
        class="px-3 py-1 rounded bg-slate-300 text-slate-800 disabled:opacity-40"
        disabled={period >= game.meta.periods}
      >+</button>
    </div>

    <!-- Player Grid -->
    <div class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-3">
      {#each game.home.players as p}
        <button
          type="button"
          class="p-3 rounded-lg bg-white border shadow flex flex-col gap-1 items-center text-center active:scale-95 transition-transform"
          onclick={() => logStat(p.id, 'GOAL')}
          oncontextmenu={(e) => { e.preventDefault(); logStat(p.id, 'SHOT'); }}
        >
          <div class="text-2xl font-bold leading-none">{p.number}</div>
          <div class="text-sm truncate w-full">{p.name}</div>
          <div class="text-xs text-slate-500 w-full">
            G:{playerTotals[p.id]?.goals ?? 0}
            &nbsp;S:{playerTotals[p.id]?.shots ?? 0}
            &nbsp;A:{playerTotals[p.id]?.assists ?? 0}
            &nbsp;B:{playerTotals[p.id]?.blocks ?? 0}
          </div>
        </button>
      {/each}
    </div>

    <!-- Opponent aggregate stat buttons -->
    <div class="grid grid-cols-4 gap-2">
      <button type="button" class="py-3 rounded bg-slate-800 text-white font-bold" onclick={() => logStat(undefined,'GOAL')}>Opp Goal</button>
      <button type="button" class="py-3 rounded bg-slate-800 text-white font-bold" onclick={() => logStat(undefined,'SHOT')}>Opp Shot</button>
      <button type="button" class="py-3 rounded bg-slate-800 text-white font-bold" onclick={() => logStat(undefined,'ASSIST')}>Opp Ast</button>
      <button type="button" class="py-3 rounded bg-slate-800 text-white font-bold" onclick={() => logStat(undefined,'BLOCK')}>Opp Block</button>
    </div>

    <!-- Controls -->
    <div class="flex gap-4 justify-center pt-4">
      <button type="button" class="px-4 py-2 rounded bg-amber-500 text-white font-semibold" onclick={undo}>Undo</button>
      <a href="/export/{game.meta.id}" class="px-4 py-2 rounded bg-blue-600 text-white font-semibold text-center">Export</a>
    </div>
  </div>
{/if}
